### ISSUE TITLE
Random error when refreshing project classpath

### ISSUE THREAD

**Issue by gayanper** [gayanper/idea-spring-tools#4]
```
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: The pipe has been ended
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at org.gap.ijplugins.spring.tools.java.ClasspathListener.sendClasspathCommand(ClasspathListener.java:195)
	at org.gap.ijplugins.spring.tools.java.ClasspathListener.register(ClasspathListener.java:87)
	at org.gap.ijplugins.spring.tools.StsLanuageClient.lambda$addClasspathListener$4(StsLanuageClient.java:130)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: The pipe has been ended
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
	at org.wso2.lsp4intellij.client.languageserver.wrapper.MessageHandler.lambda$apply$0(MessageHandler.java:45)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.request(RemoteEndpoint.java:161)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:91)
	at com.sun.proxy.$Proxy142.executeCommand(Unknown Source)
	at org.wso2.lsp4intellij.client.languageserver.requestmanager.DefaultRequestManager.executeCommand(DefaultRequestManager.java:240)
	at org.gap.ijplugins.spring.tools.java.ClasspathListener.sendClasspathCommand(ClasspathListener.java:192)
	... 8 more
Caused by: java.io.IOException: The pipe has been ended
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
	at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:123)
	at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:108)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:68)
	... 14 more
```

**Comment by gayanper** [comment]
This also happens when running a mvn build in command line which changes files due to generated source code in addition to refreshing large projects.
